export const FOOD_LISTINGS = [
  {
    id: '1', restaurantId: 'r1', restaurantName: 'Spice Garden',
    cuisine: 'Indian', name: 'Dal Makhani + 2 Butter Naan',
    description: 'Slow-cooked black lentils in a rich tomato-butter sauce, served with 2 freshly baked butter naans. Made this morning, still gorgeous.',
    originalPrice: 280, discountedPrice: 99,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80',
    distance: 0.5, address: 'CG Road, Ahmedabad',
    pickupSlots: ['6:00 PM – 6:30 PM', '6:30 PM – 7:00 PM', '7:00 PM – 7:30 PM'],
    expiresInMinutes: 45, quantity: 8, quantityLeft: 3,
    tags: ['Veg', 'Spicy'], rating: 4.7, reviews: 89, co2Saved: 0.8, category: 'Indian',
  },
  {
    id: '2', restaurantId: 'r2', restaurantName: 'Artisan Bakes',
    cuisine: 'Bakery', name: 'Assorted Pastry Box (6 pcs)',
    description: 'A surprise selection of 6 freshly baked morning pastries — croissants, Danish, muffins. Each box is different. Zero repeats.',
    originalPrice: 480, discountedPrice: 180,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80',
    distance: 1.2, address: 'Satellite, Ahmedabad',
    pickupSlots: ['5:00 PM – 5:30 PM', '5:30 PM – 6:00 PM'],
    expiresInMinutes: 120, quantity: 4, quantityLeft: 4,
    tags: ['Veg', 'Contains Egg'], rating: 4.9, reviews: 214, co2Saved: 1.4, category: 'Bakery',
  },
  {
    id: '3', restaurantId: 'r3', restaurantName: 'Tokyo Bites',
    cuisine: 'Japanese', name: 'Sushi Platter (10 pcs)',
    description: '10-piece assorted sushi platter with salmon, tuna, and cucumber rolls. Made fresh at noon. Best before 8 PM.',
    originalPrice: 650, discountedPrice: 249,
    image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&q=80',
    distance: 2.1, address: 'Prahlad Nagar, Ahmedabad',
    pickupSlots: ['7:00 PM – 7:30 PM', '7:30 PM – 8:00 PM'],
    expiresInMinutes: 180, quantity: 3, quantityLeft: 2,
    tags: ['Non-Veg'], rating: 4.8, reviews: 156, co2Saved: 2.1, category: 'Japanese',
  },
  {
    id: '4', restaurantId: 'r4', restaurantName: 'Woodfire Pizza',
    cuisine: 'Italian', name: 'Margherita Pizza (12")',
    description: 'Wood-fired margherita with San Marzano tomatoes, fresh mozzarella, and basil. From our evening batch. Still warm, definitely perfect.',
    originalPrice: 399, discountedPrice: 149,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80',
    distance: 0.9, address: 'Bodakdev, Ahmedabad',
    pickupSlots: ['8:00 PM – 8:30 PM', '8:30 PM – 9:00 PM'],
    expiresInMinutes: 60, quantity: 6, quantityLeft: 5,
    tags: ['Veg'], rating: 4.6, reviews: 342, co2Saved: 1.0, category: 'Italian',
  },
  {
    id: '5', restaurantId: 'r5', restaurantName: 'Burger Republic',
    cuisine: 'American', name: 'Double Smash Burger + Fries',
    description: 'Two smashed beef patties, American cheese, pickles, special sauce. Side of crispy seasoned fries. No compromises.',
    originalPrice: 450, discountedPrice: 175,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
    distance: 1.5, address: 'SG Highway, Ahmedabad',
    pickupSlots: ['9:00 PM – 9:30 PM', '9:30 PM – 10:00 PM'],
    expiresInMinutes: 90, quantity: 10, quantityLeft: 7,
    tags: ['Non-Veg'], rating: 4.4, reviews: 521, co2Saved: 1.6, category: 'American',
  },
  {
    id: '6', restaurantId: 'r6', restaurantName: 'Garden of Greens',
    cuisine: 'Healthy', name: 'Power Bowl (Quinoa + Avocado)',
    description: 'Quinoa, roasted chickpeas, avocado, cherry tomatoes, and tahini dressing. Nutrient-dense. Actually filling.',
    originalPrice: 320, discountedPrice: 120,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
    distance: 0.7, address: 'Thaltej, Ahmedabad',
    pickupSlots: ['6:00 PM – 6:30 PM', '6:30 PM – 7:00 PM'],
    expiresInMinutes: 30, quantity: 5, quantityLeft: 2,
    tags: ['Veg', 'Healthy', 'Vegan'], rating: 4.8, reviews: 97, co2Saved: 0.6, category: 'Healthy',
  },
  {
    id: '7', restaurantId: 'r7', restaurantName: 'Biryani House',
    cuisine: 'Indian', name: 'Hyderabadi Chicken Biryani (2 servings)',
    description: 'Authentic dum biryani. Tender chicken, aromatic basmati, slow-cooked spices. Feeds 2. This one disappears fast.',
    originalPrice: 520, discountedPrice: 199,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&q=80',
    distance: 1.8, address: 'Maninagar, Ahmedabad',
    pickupSlots: ['7:30 PM – 8:00 PM', '8:00 PM – 8:30 PM'],
    expiresInMinutes: 150, quantity: 7, quantityLeft: 4,
    tags: ['Non-Veg', 'Spicy'], rating: 4.9, reviews: 612, co2Saved: 1.8, category: 'Indian',
  },
  {
    id: '8', restaurantId: 'r8', restaurantName: 'Noodle Bar',
    cuisine: 'Thai', name: 'Pad Thai + Spring Rolls',
    description: 'Classic pad thai with rice noodles, prawns, and crushed peanuts. Plus 3 crispy veggie spring rolls. Last one today.',
    originalPrice: 380, discountedPrice: 149,
    image: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=600&q=80',
    distance: 3.2, address: 'Vastrapur, Ahmedabad',
    pickupSlots: ['7:00 PM – 7:30 PM'],
    expiresInMinutes: 75, quantity: 4, quantityLeft: 1,
    tags: ['Non-Veg'], rating: 4.5, reviews: 178, co2Saved: 1.1, category: 'Thai',
  },
];

export const MY_ORDERS = [
  {
    id: 'o1', orderId: '#ZH00124', status: 'active', subStatus: 'ready_for_pickup',
    foodName: 'Pad Thai + Spring Rolls', restaurantName: 'Noodle Bar',
    restaurantAddress: 'Vastrapur, Ahmedabad',
    image: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=400&q=80',
    price: 149, pickupSlot: '7:00 PM – 7:30 PM', orderTime: '6:42 PM', date: 'Today',
    savings: 231, co2Saved: 1.1,
  },
  {
    id: 'o2', orderId: '#ZH00119', status: 'active', subStatus: 'confirmed',
    foodName: 'Sushi Platter (10 pcs)', restaurantName: 'Tokyo Bites',
    restaurantAddress: 'Prahlad Nagar, Ahmedabad',
    image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&q=80',
    price: 249, pickupSlot: '7:30 PM – 8:00 PM', orderTime: '7:05 PM', date: 'Today',
    savings: 401, co2Saved: 2.1,
  },
  {
    id: 'o3', orderId: '#ZH00108', status: 'history', subStatus: 'completed',
    foodName: 'Assorted Pastry Box (6 pcs)', restaurantName: 'Artisan Bakes',
    restaurantAddress: 'Satellite, Ahmedabad',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80',
    price: 180, pickupSlot: '5:30 PM – 6:00 PM', orderTime: '5:10 PM', date: 'Yesterday',
    savings: 300, co2Saved: 1.4, rating: 5,
  },
  {
    id: 'o4', orderId: '#ZH00094', status: 'history', subStatus: 'completed',
    foodName: 'Margherita Pizza (12")', restaurantName: 'Woodfire Pizza',
    restaurantAddress: 'Bodakdev, Ahmedabad',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80',
    price: 149, pickupSlot: '8:00 PM – 8:30 PM', orderTime: '7:45 PM', date: '2 days ago',
    savings: 250, co2Saved: 1.0, rating: 4,
  },
  {
    id: 'o5', orderId: '#ZH00087', status: 'history', subStatus: 'completed',
    foodName: 'Hyderabadi Chicken Biryani', restaurantName: 'Biryani House',
    restaurantAddress: 'Maninagar, Ahmedabad',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=80',
    price: 199, pickupSlot: '8:00 PM – 8:30 PM', orderTime: '7:30 PM', date: '3 days ago',
    savings: 321, co2Saved: 1.8, rating: 5,
  },
];

export const RESTAURANT_STATS = {
  todayMealsSaved: 23, todayEarnings: 3420, todayCO2Saved: 28.6,
  weeklyMealsSaved: 142, weeklyEarnings: 18650, weeklyCO2Saved: 164.2,
  totalMealsSaved: 1847, totalCO2Saved: 2104.8,
};

export const RESTAURANT_LISTINGS = [
  {
    id: 'rl1', name: 'Dal Makhani + 2 Butter Naan',
    originalPrice: 280, discountedPrice: 99,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    quantityLeft: 3, totalQuantity: 8,
    pickupSlot: '6:00 PM – 7:30 PM', expiresInMinutes: 45,
    status: 'active', ordersReceived: 5,
  },
  {
    id: 'rl2', name: 'Chicken Biryani (Single)',
    originalPrice: 280, discountedPrice: 109,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=80',
    quantityLeft: 0, totalQuantity: 5,
    pickupSlot: '7:00 PM – 8:00 PM', expiresInMinutes: 0,
    status: 'soldout', ordersReceived: 5,
  },
  {
    id: 'rl3', name: 'Paneer Tikka Masala + Rice',
    originalPrice: 320, discountedPrice: 119,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    quantityLeft: 7, totalQuantity: 10,
    pickupSlot: '5:30 PM – 6:30 PM', expiresInMinutes: 120,
    status: 'active', ordersReceived: 3,
  },
];

export const RESTAURANT_ORDERS = [
  {
    id: 'ro1', orderId: '#ZH00124', customerName: 'Riya M.',
    foodName: 'Dal Makhani + 2 Butter Naan', quantity: 1, price: 99,
    pickupSlot: '6:00 PM – 6:30 PM', status: 'ready_for_pickup', orderTime: '5:42 PM',
  },
  {
    id: 'ro2', orderId: '#ZH00123', customerName: 'Arjun S.',
    foodName: 'Dal Makhani + 2 Butter Naan', quantity: 1, price: 99,
    pickupSlot: '6:30 PM – 7:00 PM', status: 'confirmed', orderTime: '6:01 PM',
  },
  {
    id: 'ro3', orderId: '#ZH00122', customerName: 'Priya J.',
    foodName: 'Paneer Tikka Masala + Rice', quantity: 1, price: 119,
    pickupSlot: '5:30 PM – 6:00 PM', status: 'completed', orderTime: '5:15 PM',
  },
  {
    id: 'ro4', orderId: '#ZH00121', customerName: 'Kabir P.',
    foodName: 'Paneer Tikka Masala + Rice', quantity: 1, price: 119,
    pickupSlot: '6:00 PM – 6:30 PM', status: 'confirmed', orderTime: '5:30 PM',
  },
];

export const CATEGORIES = [
  { id: 'All', label: 'All', emoji: '🍽️' },
  { id: 'Indian', label: 'Indian', emoji: '🍛' },
  { id: 'Bakery', label: 'Bakery', emoji: '🥐' },
  { id: 'Italian', label: 'Italian', emoji: '🍕' },
  { id: 'Japanese', label: 'Japanese', emoji: '🍣' },
  { id: 'American', label: 'American', emoji: '🍔' },
  { id: 'Healthy', label: 'Healthy', emoji: '🥗' },
  { id: 'Thai', label: 'Thai', emoji: '🍜' },
];
